### ISSUE TITLE
Discussion of approaches

### ISSUE THREAD

**Issue by dhoer** [ai-traders/cookbook-windows_gui_service#1]
I ran across this today looking for something else.   I especially like the elevated permission part which is something I haven't thought about.  I also liked how you explained why you are doing this.

I have similar code in selenium cookbook and was planning to move it out to its own cookbook as part of the mac support refactor.  I have already started creating a windows_autologin cookbook but haven't released it yet.   

I was planning to create a similar cookbook that could be used like this:

```
user
group
windows_home
windows_gui_service
  windows_autologin
  windows_shortcut
reboot
```

I like using the separation of concern pattern (SoC).  This allows for maximum flexibility without the need to fork. So user, group, windows_home, and reboot would be called outside of the cookbook since it is not a direct concern.  The windows_gui_service would call windows_autologin and windows_shortcut inside the create action.

Calling windows_gui_service would look something like this:

```
windows_gui_service 'service_name' do
  executable 'C:/Windows/notepad.exe'
  username 'username'
  password 'password'
  action  :create
  elevate true  
end
```

I also like to maybe have an optional `stdout_path` and `stderr_path` for logging.

If you are interested in this approach, I would be happy work with you.  If not, no problem.  But I would like to use you elevation code, if you didn't mind.

BTW, there is a way to add recipes in a lwrp action so you don't have to include them:

```
recipe_eval do
  run_context.include_recipe 'selenium::server'
  ...
end
```

It works on Chef 11 and 12.

**Comment by tomzo** [comment]
Sounds OK to me. `stdout_path` and `sterr_path` would be nice.
I did not put much effort into handling user, group and windows home. I think it should be improved if that's what you need.

But how do you expect autologin to work when somebody declares `windows_gui_service` more than once with different username and password?
There can be only one user to autologin when windows boots. I intentionally added them as attributes to enforce consistency. 

The elevation code is part of some stackoverflow answer, which I cannot find right now. Feel free to use it.

Thanks for the tip with including recipes. I think it would make sense to just include all recipes in resources.

**Comment by dhoer** [comment]
You bring up a good point. I will refactor my mac and win autologin lwrp's to be recipes where `default` enables and `remove` disables autologin.

I think that will still work for the following scenario where; selenium_node creates autologin for user passed, and windows_display overwrites it with `rdp_local` user (from https://github.com/dhoer/chef-selenium/blob/master/test/fixtures/cookbooks/selenium_test/recipes/node.rb#L78-94):

``` ruby
selenium_node 'selenium_node' do
  username 'Administrator' if platform?('windows')
  password 'password' if platform?('windows')
  capabilities capabilities
  jvm_args '-Xms1024m'
  action :install
end

if platform?('windows')
  # Call windows_display after selenium_node because windows_display will override auto-login created by
  # selenium_node.
  windows_display 'Administrator' do
    password 'password'
    width 1440
    height 900
  end
end
```

So the following code (from https://github.com/dhoer/chef-selenium/blob/master/libraries/default.rb#L87-97):

``` ruby
def autologon(username, password, domain)
  registry_key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' do
    values [
      { name: 'AutoAdminLogon', type: :string, data: '1' },
      { name: 'DefaultUsername', type: :string, data: username },
      { name: 'DefaultPassword', type: :string, data: password },
      { name: 'DefaultDomainName', type: :string, data: domain }
    ]
    action :create
  end
end
```

Would be replaced with:

``` ruby
node.set['windows_autologin']['username'] =  whatever
node.set['windows_autologin']['password'] = whatever
node.set['windows_autologin']['domain'] = whatever
recipe_eval do
    run_context.include_recipe 'windows_autologin'
end
```

So would the following:

https://github.com/dhoer/chef-windows_display/blob/master/providers/default.rb#L57-66

I don't think making it a recipe vs a lwrp will make a difference.  Let me know if you think otherwise.

---

Here is an example of why I think user and group should be removed from the code.  Here I need to assign the user to multiple groups in order for rdp to work (from https://github.com/dhoer/chef-windows_display/blob/master/providers/default.rb#L11-25):

``` ruby
    user rdp_user do
      password rdp_password
    end

    new_resource.rdp_groups.each do |group|
      group group do
        members [rdp_user]
        append true
        action :modify
      end
    end

    windows_home rdp_user do
      password rdp_password
    end
```

**Comment by tomzo** [comment]
> I don't think making it a recipe vs a lwrp will make a difference. Let me know if you think otherwise.

Well it would probably work. Its just that is not _nice_ because it may lead to repeating code and inconsistencies. 

> Here is an example of why I think user and group should be removed from the code.

You mean remove user handling in windows_gui_service cookbook? 
If it was removed entirely then cookbook by itself would be broken.
Instead I could make [this resource](https://github.com/ai-traders/cookbook-windows_gui_service/blob/master/recipes/autologin.rb#L27) conditional based on attribute `node[:windows_gui_service][:handle_user]`. By default it would configure user, just to be safe. Then you can overload attribute higher as obviously needed.

In my opinion user and group handling is one of most confusing parts of working with chef. Cookbook which should actually be responsible for setting up users often changes as use cases do. Which leads to situation like above.

**Comment by dhoer** [comment]
Providing a test fixture as an example of how to use it with user and group
might help.  I use Administrator user a lot even though I shouldn't.  So I
wouldn't need to create a user most times.  I also have to add group
privileges on windows platforms to get a user to do what I want, so I don't
know how gui service would manage all of the different things you can do
with groups and users.  I have to think about it over the weekend.

**Comment by dhoer** [comment]
I could live with user creation if a block would prevent it from creating a user if it already exists.

**Comment by dhoer** [comment]
Finished refactoring my mac and win autologin lwrp's to be recipes.  Thanks for the feedback.

**Comment by tomzo** [comment]
Thanks as well
